-- DEPRECATED: Use supabase.language-functions.schema.sql instead.
-- This file is kept for reference only. The sentence_purposes / sentence_structures /
-- sentence_examples tables were replaced by language_functions / function_structures /
-- function_phrases / function_examples.
